/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CraftsRouteImport } from './routes/crafts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as ListingRouteImport } from './routes/listing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ProfileCategoryRouteImport } from './routes/profile.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsRoute = CraftsRouteImport.update({
  id: '/crafts',
  path: '/crafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingRoute = ListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingRoute,
} as any)
const ProfileCategoryRoute = ProfileCategoryRouteImport.update({
  id: '/profile/$category',
  path: '/profile/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crafts': typeof CraftsRoute
  '/dashboard': typeof DashboardRoute
  '/dates': typeof DatesRoute
  '/listing': typeof ListingRouteWithChildren
  '/login': typeof LoginRoute
  '/listing/$id': typeof ListingIdRoute
  '/profile/$category': typeof ProfileCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crafts': typeof CraftsRoute
  '/dashboard': typeof DashboardRoute
  '/dates': typeof DatesRoute
  '/listing': typeof ListingRouteWithChildren
  '/login': typeof LoginRoute
  '/listing/$id': typeof ListingIdRoute
  '/profile/$category': typeof ProfileCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crafts': typeof CraftsRoute
  '/dashboard': typeof DashboardRoute
  '/dates': typeof DatesRoute
  '/listing': typeof ListingRouteWithChildren
  '/login': typeof LoginRoute
  '/listing/$id': typeof ListingIdRoute
  '/profile/$category': typeof ProfileCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/crafts'
    | '/dashboard'
    | '/dates'
    | '/listing'
    | '/login'
    | '/listing/$id'
    | '/profile/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/crafts'
    | '/dashboard'
    | '/dates'
    | '/listing'
    | '/login'
    | '/listing/$id'
    | '/profile/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crafts'
    | '/dashboard'
    | '/dates'
    | '/listing'
    | '/login'
    | '/listing/$id'
    | '/profile/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CraftsRoute: typeof CraftsRoute
  DashboardRoute: typeof DashboardRoute
  DatesRoute: typeof DatesRoute
  ListingRoute: typeof ListingRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileCategoryRoute: typeof ProfileCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts': {
      id: '/crafts'
      path: '/crafts'
      fullPath: '/crafts'
      preLoaderRoute: typeof CraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing': {
      id: '/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof ListingRoute
    }
    '/profile/$category': {
      id: '/profile/$category'
      path: '/profile/$category'
      fullPath: '/profile/$category'
      preLoaderRoute: typeof ProfileCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListingRouteChildren {
  ListingIdRoute: typeof ListingIdRoute
}

const ListingRouteChildren: ListingRouteChildren = {
  ListingIdRoute: ListingIdRoute,
}

const ListingRouteWithChildren =
  ListingRoute._addFileChildren(ListingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CraftsRoute: CraftsRoute,
  DashboardRoute: DashboardRoute,
  DatesRoute: DatesRoute,
  ListingRoute: ListingRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileCategoryRoute: ProfileCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
